Repository Epsor/mongodb-wrapper, pull requests merged in 2019-11, with the labels that each got.

#18 Fix/mongo errors
  index.d.ts
  package-lock.json
  package.json
Labels: enhancement

#23 Feat/add mongo duplicate entry update one push
  package-lock.json
  package.json
  src/__tests__/mongoCollectionWrapper.test.js
  src/mongoCollectionWrapper.js
Labels: enhancement

#24 Fix/safe insert sub fields
  package-lock.json
  package.json
  src/__tests__/mongoCollectionWrapper.test.js
  src/mongoCollectionWrapper.js
Labels: bug

#25 Fix/limit size
  package-lock.json
  package.json
  src/__tests__/mongoCollectionWrapper.test.js
  src/mongoCollectionWrapper.js
Labels: bug, enhancement
